import type { NextPage } from "next";
import { useState } from "react";

import Head from "next/head";
import { FormEvent } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [url, setUrl] = useState<string>("");
  const [shortUrl, setShortUrl] = useState<string>("");

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    const response = await fetch("api/shorten", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ url }),
    });

    const value = await response.json();
    setShortUrl(
      `${document.location.protocol}//${document.location.host}/${value.shortURL}`
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper}>
          <h1 className={styles.title}>Link Shortener</h1>
          <p className={styles.description}>
            Simple url shortening app using Vercel Edge Functions, Upstash Redis
            and NextJS
          </p>

          <form onSubmit={handleSubmit}>
            <div className={styles.search}>
              <input
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="Enter url here"
                type="url"
                required
                className={styles.searchInput}
              />
            </div>

            <button type="submit" className={styles.searchButton}>
              Shorten Link
            </button>
          </form>
          {shortUrl !== "" && (
            <a
              target="_blank"
              href={shortUrl}
              rel="noopener noreferrer"
              className={styles.url}
            >
              <p>{shortUrl}</p>
            </a>
          )}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
